name: Codacy

on:
  push:
    paths-ignore:
      - '/vendor/**'
      - '/dashboard/node_modules/**'

jobs:
  codacy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Codacy Coverage Reporter
        run: curl -Ls -o codacy-coverage-reporter https://coverage.codacy.com/codacy-coverage-reporter-LATEST-linux
      
      - name: Make Codacy Coverage Reporter executable
        run: chmod +x codacy-coverage-reporter
      
      - name: Run Codacy Coverage Reporter
        run: ./codacy-coverage-reporter report -l PHP -r coverage.xml
```