name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Install Node.js and npm
          uses: actions/setup-node@v3
          with:
            node-version: '14'
  
        - name: Install dependencies
          run: npm install
          working-directory: dashboard
  
        - name: Run ESLint with auto-fix
          run: npx eslint --fix --config .eslintrc.yml .
          working-directory: dashboard