name: Static Code Analysis

on: [push]

jobs:
  Run-Static-Code-Analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - uses: php-actions/phpstan@v3
        with:
          level: 8
          args: --no-progress
          path: dashboard
